# See also https://www.npmjs.com/package/@netlify/plugin-nextjs
[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"

[[plugins]]
  package = "@sentry/netlify-build-plugin"

  [plugins.inputs]
    sentryOrg = "mission-bit"
    sentryProject = "donatemissionbitorg"
