name: cron

on:
  workflow_dispatch:
  schedule:
    # Every 10 minutes
    - cron: "*/10 * * * *"

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - run: npm install
      - run: npm run cron
        env:
          EVENTBRITE_TOKEN: ${{ secrets.EVENTBRITE_TOKEN }}
          GIVEBUTTER_API_KEY: ${{ secrets.GIVEBUTTER_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          SALESFORCE_CLIENT_ID: ${{ secrets.SALESFORCE_CLIENT_ID }}
          SALESFORCE_CLIENT_SECRET: ${{ secrets.SALESFORCE_CLIENT_SECRET }}
          SALESFORCE_RECORD_TYPE_ID_DONATION: ${{ secrets.SALESFORCE_RECORD_TYPE_ID_DONATION }}
          SALESFORCE_RECORD_TYPE_ID_MATCHING_GIFT: ${{ secrets.SALESFORCE_RECORD_TYPE_ID_MATCHING_GIFT }}
          SALESFORCE_RECORD_TYPE_ID_SPECIAL_EVENT_REVENUE: ${{ secrets.SALESFORCE_RECORD_TYPE_ID_SPECIAL_EVENT_REVENUE }}
          SALESFORCE_RECORD_TYPE_ID_GENERAL: ${{ secrets.SALESFORCE_RECORD_TYPE_ID_GENERAL }}
          SALESFORCE_RECORD_TYPE_ID_DEFAULT: ${{ secrets.SALESFORCE_RECORD_TYPE_ID_DEFAULT }}
          SALESFORCE_RECORD_TYPE_ID_ORGANIZATION: ${{ secrets.SALESFORCE_RECORD_TYPE_ID_ORGANIZATION }}
          SALESFORCE_RECORD_TYPE_ID_HOUSEHOLD: ${{ secrets.SALESFORCE_RECORD_TYPE_ID_HOUSEHOLD }}
          SALESFORCE_INSTANCE_URL: ${{ secrets.SALESFORCE_INSTANCE_URL }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          STRIPE_PK: ${{ secrets.STRIPE_PK_LIVE }}
          STRIPE_SK: ${{ secrets.STRIPE_SK_LIVE }}
          STRIPE_WEBHOOK_SIGNING_SECRET: ${{ secrets.STRIPE_WEBHOOK_SIGNING_SECRET_LIVE }}
          SUPABASE_JWT_SECRET: ${{ secrets.SUPABASE_JWT_SECRET }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          SUPABASE_PRIVATE_API_KEY: ${{ secrets.SUPABASE_PRIVATE_API_KEY }}
          SUPABASE_PROJECT_URL: ${{ secrets.SUPABASE_PROJECT_URL }}
          SUPABASE_PUBLIC_API_KEY: ${{ secrets.SUPABASE_PUBLIC_API_KEY }}
